// SPDX-License-Identifier: MIT
// Copyright (c) 2026 zgock999

using BitConverter = System.BitConverter;
using NUnit.Framework;
using UnityEngine;
namespace zgock.ShapeSync.StackMachine.Tests.Spec18
{
 public sealed class AtlasMeshStructureOracleTests
 {
  [Test] public void TryValidate_MapsOnlyTargetSubmeshAndRejectsStructureOrScopeChanges()
  {
   Mesh source=Mesh(); Mesh output=Object.Instantiate(source); var cell=new AtlasLayoutCell(new MaterialId("r","a"),0,0,0,256,256,0); var state=new AtlasMeshStructureOracle.MaterialState(new Vector4(1,1,0,0),new Vector4(1,1,0,0)); output.uv=new[]{AtlasUvTransform.Apply(source.uv[0],Vector2.one,Vector2.zero,cell,512),AtlasUvTransform.Apply(source.uv[1],Vector2.one,Vector2.zero,cell,512),AtlasUvTransform.Apply(source.uv[2],Vector2.one,Vector2.zero,cell,512),source.uv[3],source.uv[4],source.uv[5]}; var c=new[]{new AtlasMeshStructureOracle.Context(new MaterialId("r","a"),0,true,cell,512,Vector2.one,Vector2.zero,state,false,AtlasTextureSemantic.BaseColor),new AtlasMeshStructureOracle.Context(new MaterialId("r","b"),1,false,null,0,Vector2.one,Vector2.zero,state,true,AtlasTextureSemantic.Normal)};
   Assert.That(AtlasMeshStructureOracle.TryValidate(source,output,c,out var ok),Is.True,ok?.message); var changed=output.uv; changed[4]=new Vector2(.3f,.7f); output.uv=changed; Assert.That(AtlasMeshStructureOracle.TryValidate(source,output,c,out var scope),Is.False); Assert.That(scope.domainCode,Is.EqualTo("AtlasMeshStructureUvScope")); Object.DestroyImmediate(source);Object.DestroyImmediate(output);
  }
  [Test] public void TryValidate_RejectsInvalidContextAndSharedTargetVertex()
  {
   Mesh source=Mesh(); Mesh output=Object.Instantiate(source); var cell=new AtlasLayoutCell(new MaterialId("r","a"),0,0,0,256,256,0); var invalid=new[]{new AtlasMeshStructureOracle.Context(new MaterialId("r","other"),0,true,cell,512,Vector2.one,Vector2.zero),new AtlasMeshStructureOracle.Context(new MaterialId("r","b"),1,false,null,0,Vector2.one,Vector2.zero)};
   Assert.That(AtlasMeshStructureOracle.TryValidate(source,output,invalid,out var context),Is.False); Assert.That(context.domainCode,Is.EqualTo("AtlasMeshStructureContextInvalid"));
   var invalidSemantic=new[]{new AtlasMeshStructureOracle.Context(new MaterialId("r","a"),0,false,null,0,Vector2.one,Vector2.zero,false,(AtlasTextureSemantic)99),new AtlasMeshStructureOracle.Context(new MaterialId("r","b"),1,false,null,0,Vector2.one,Vector2.zero)}; Assert.That(AtlasMeshStructureOracle.TryValidate(source,output,invalidSemantic,out var semantic),Is.False); Assert.That(semantic.domainCode,Is.EqualTo("AtlasMeshStructureContextInvalid"));
   var materialState=new AtlasMeshStructureOracle.MaterialState(new Vector4(1,1,0,0),new Vector4(1,1,0,0)); output.uv=source.uv; var valid=new[]{new AtlasMeshStructureOracle.Context(new MaterialId("r","a"),0,true,cell,512,Vector2.one,Vector2.zero,materialState,false,AtlasTextureSemantic.BaseColor),new AtlasMeshStructureOracle.Context(new MaterialId("r","b"),1,false,null,0,Vector2.one,Vector2.zero,materialState,false,AtlasTextureSemantic.Normal)}; source.SetTriangles(new[]{0,1,2},1); output.SetTriangles(new[]{0,1,2},1); Assert.That(AtlasMeshStructureOracle.TryValidate(source,output,valid,out var shared),Is.False); Assert.That(shared.domainCode,Is.EqualTo("AtlasSharedVertex")); Object.DestroyImmediate(source);Object.DestroyImmediate(output);
  }
  [Test] public void TryValidate_PreservesRendererSlotOrderAndIdentityTokens()
  {
   Mesh source=Mesh(); Mesh output=Object.Instantiate(source); var cell=new AtlasLayoutCell(new MaterialId("r","a"),0,0,0,256,256,0); var materialState=new AtlasMeshStructureOracle.MaterialState(new Vector4(1,1,0,0),new Vector4(1,1,0,0)); output.uv=new[]{AtlasUvTransform.Apply(source.uv[0],Vector2.one,Vector2.zero,cell,512),AtlasUvTransform.Apply(source.uv[1],Vector2.one,Vector2.zero,cell,512),AtlasUvTransform.Apply(source.uv[2],Vector2.one,Vector2.zero,cell,512),source.uv[3],source.uv[4],source.uv[5]}; var contexts=new[]{new AtlasMeshStructureOracle.Context(new MaterialId("r","a"),0,true,cell,512,Vector2.one,Vector2.zero,materialState,false,AtlasTextureSemantic.BaseColor),new AtlasMeshStructureOracle.Context(new MaterialId("r","b"),1,false,null,0,Vector2.one,Vector2.zero,materialState,false,AtlasTextureSemantic.Normal)}; var state=new AtlasMeshStructureOracle.RendererState(new[]{new MaterialId("r","a"),new MaterialId("r","b")},"root","avatar");
   Assert.That(AtlasMeshStructureOracle.TryValidate(source,output,contexts,state,state,out var ok),Is.True,ok?.message); var reordered=new AtlasMeshStructureOracle.RendererState(new[]{new MaterialId("r","b"),new MaterialId("r","a")},"root","avatar"); Assert.That(AtlasMeshStructureOracle.TryValidate(source,output,contexts,state,reordered,out var slots),Is.False); Assert.That(slots.domainCode,Is.EqualTo("AtlasMeshStructureMaterialSlotsChanged")); var changedRoot=new AtlasMeshStructureOracle.RendererState(new[]{new MaterialId("r","a"),new MaterialId("r","b")},"other","avatar"); Assert.That(AtlasMeshStructureOracle.TryValidate(source,output,contexts,state,changedRoot,out var root),Is.False); Assert.That(root.domainCode,Is.EqualTo("AtlasMeshStructureRendererStateChanged")); Object.DestroyImmediate(source);Object.DestroyImmediate(output);
  }
  [Test] public void TryValidate_RejectsBindposeBoneWeightAndBlendShapeChanges()
  {
   Mesh source=Mesh(); source.bindposes=new[]{Matrix4x4.identity}; var weights=new BoneWeight[6]; for(int i=0;i<weights.Length;i++) weights[i]=new BoneWeight{boneIndex0=0,weight0=1f}; source.boneWeights=weights; var delta=new Vector3[6]; source.AddBlendShapeFrame("shape",100f,delta,delta,delta); Mesh output=Object.Instantiate(source); var contexts=new[]{new AtlasMeshStructureOracle.Context(new MaterialId("r","a"),0,false,null,0,Vector2.one,Vector2.zero),new AtlasMeshStructureOracle.Context(new MaterialId("r","b"),1,false,null,0,Vector2.one,Vector2.zero)};
   output.bindposes=new[]{Matrix4x4.zero}; Assert.That(AtlasMeshStructureOracle.TryValidate(source,output,contexts,out var bind),Is.False); Assert.That(bind.domainCode,Is.EqualTo("AtlasMeshStructureBindposeChanged")); output.bindposes=source.bindposes; var changed=output.boneWeights; changed[0].weight0=.5f; output.boneWeights=changed; Assert.That(AtlasMeshStructureOracle.TryValidate(source,output,contexts,out var bone),Is.False); Assert.That(bone.domainCode,Is.EqualTo("AtlasMeshStructureBoneWeightChanged")); output.boneWeights=source.boneWeights; output.ClearBlendShapes(); Assert.That(AtlasMeshStructureOracle.TryValidate(source,output,contexts,out var blend),Is.False); Assert.That(blend.domainCode,Is.EqualTo("AtlasMeshStructureChanged")); Object.DestroyImmediate(source);Object.DestroyImmediate(output);
  }
  [Test] public void TryValidate_RejectsMissingOrDuplicateContextAndAvatarChange()
  {
   Mesh source=Mesh(); Mesh output=Object.Instantiate(source); var materialState=new AtlasMeshStructureOracle.MaterialState(new Vector4(1,1,0,0),new Vector4(1,1,0,0)); var contexts=new[]{new AtlasMeshStructureOracle.Context(new MaterialId("r","a"),0,false,null,0,Vector2.one,Vector2.zero,materialState,false,AtlasTextureSemantic.BaseColor)}; Assert.That(AtlasMeshStructureOracle.TryValidate(source,output,contexts,out var missing),Is.False); Assert.That(missing.domainCode,Is.EqualTo("AtlasMeshStructureContextMissing")); var duplicated=new[]{contexts[0],new AtlasMeshStructureOracle.Context(new MaterialId("r","b"),0,false,null,0,Vector2.one,Vector2.zero,materialState,false,AtlasTextureSemantic.Normal)}; Assert.That(AtlasMeshStructureOracle.TryValidate(source,output,duplicated,out var duplicate),Is.False); Assert.That(duplicate.domainCode,Is.EqualTo("AtlasMeshStructureContextInvalid")); var full=new[]{contexts[0],new AtlasMeshStructureOracle.Context(new MaterialId("r","b"),1,false,null,0,Vector2.one,Vector2.zero,materialState,false,AtlasTextureSemantic.Normal)}; var before=new AtlasMeshStructureOracle.RendererState(new[]{new MaterialId("r","a"),new MaterialId("r","b")},"root","avatar"); var after=new AtlasMeshStructureOracle.RendererState(new[]{new MaterialId("r","a"),new MaterialId("r","b")},"root","other"); Assert.That(AtlasMeshStructureOracle.TryValidate(source,output,full,before,after,out var avatar),Is.False); Assert.That(avatar.domainCode,Is.EqualTo("AtlasMeshStructureRendererStateChanged")); Object.DestroyImmediate(source);Object.DestroyImmediate(output);
  }
  [Test] public void TryValidate_RejectsSameShapeBlendShapeDeltaChange()
  {
   Mesh source=Mesh(); var zero=new Vector3[6]; source.AddBlendShapeFrame("shape",100f,zero,zero,zero); Mesh output=Object.Instantiate(source); output.ClearBlendShapes(); var changed=new Vector3[6]; changed[0]=Vector3.right; output.AddBlendShapeFrame("shape",100f,changed,zero,zero); var contexts=new[]{new AtlasMeshStructureOracle.Context(new MaterialId("r","a"),0,false,null,0,Vector2.one,Vector2.zero),new AtlasMeshStructureOracle.Context(new MaterialId("r","b"),1,false,null,0,Vector2.one,Vector2.zero)};
   Assert.That(AtlasMeshStructureOracle.TryValidate(source,output,contexts,out var diagnostic),Is.False); Assert.That(diagnostic.domainCode,Is.EqualTo("AtlasMeshStructureBlendShapeChanged")); Object.DestroyImmediate(source);Object.DestroyImmediate(output);
  }
  [Test] public void TryValidate_RequiresLayoutMatchingContextAndKeepsExcludedContextUnchanged()
  {
   Mesh source=Mesh(); Mesh output=Object.Instantiate(source); var target=new AtlasLayoutCell(new MaterialId("r","a"),0,0,0,256,256,0); var layout=new AtlasLayoutResult(512,new[]{new AtlasSemanticPage(0,AtlasTextureSemantic.BaseColor,512),new AtlasSemanticPage(0,AtlasTextureSemantic.Normal,512)},new[]{target}); var materialState=new AtlasMeshStructureOracle.MaterialState(new Vector4(1,1,0,0),new Vector4(1,1,0,0)); output.uv=new[]{AtlasUvTransform.Apply(source.uv[0],Vector2.one,Vector2.zero,target,512),AtlasUvTransform.Apply(source.uv[1],Vector2.one,Vector2.zero,target,512),AtlasUvTransform.Apply(source.uv[2],Vector2.one,Vector2.zero,target,512),source.uv[3],source.uv[4],source.uv[5]}; var contexts=new[]{new AtlasMeshStructureOracle.Context(new MaterialId("r","a"),0,true,target,512,Vector2.one,Vector2.zero,materialState,false,AtlasTextureSemantic.BaseColor),new AtlasMeshStructureOracle.Context(new MaterialId("r","b"),1,false,null,0,Vector2.one,Vector2.zero,materialState,true,AtlasTextureSemantic.Normal)};
   var state=new AtlasMeshStructureOracle.RendererState(new[]{new MaterialId("r","a"),new MaterialId("r","b")},"root","avatar"); Assert.That(AtlasMeshStructureOracle.TryValidateForAtlasAcceptance(source,output,contexts,layout,state,state,out var ok),Is.True,ok?.message); var reordered=new AtlasMeshStructureOracle.RendererState(new[]{new MaterialId("r","b"),new MaterialId("r","a")},"root","avatar"); Assert.That(AtlasMeshStructureOracle.TryValidateForAtlasAcceptance(source,output,contexts,layout,state,reordered,out var slots),Is.False); Assert.That(slots.domainCode,Is.EqualTo("AtlasMeshStructureMaterialSlotsChanged")); var changedAvatar=new AtlasMeshStructureOracle.RendererState(new[]{new MaterialId("r","a"),new MaterialId("r","b")},"root","other"); Assert.That(AtlasMeshStructureOracle.TryValidateForAtlasAcceptance(source,output,contexts,layout,state,changedAvatar,out var avatar),Is.False); Assert.That(avatar.domainCode,Is.EqualTo("AtlasMeshStructureRendererStateChanged")); var wrong=new AtlasLayoutCell(new MaterialId("r","a"),0,256,0,256,256,0); output.uv=new[]{AtlasUvTransform.Apply(source.uv[0],Vector2.one,Vector2.zero,wrong,512),AtlasUvTransform.Apply(source.uv[1],Vector2.one,Vector2.zero,wrong,512),AtlasUvTransform.Apply(source.uv[2],Vector2.one,Vector2.zero,wrong,512),source.uv[3],source.uv[4],source.uv[5]}; var wrongContexts=new[]{new AtlasMeshStructureOracle.Context(new MaterialId("r","a"),0,true,wrong,512,Vector2.one,Vector2.zero,materialState,false,AtlasTextureSemantic.BaseColor),contexts[1]}; Assert.That(AtlasMeshStructureOracle.TryValidateForAtlasAcceptance(source,output,wrongContexts,layout,state,state,out var mismatch),Is.False); Assert.That(mismatch.domainCode,Is.EqualTo("AtlasMeshStructureLayoutContextMismatch")); var invalidExcluded=new[]{new AtlasMeshStructureOracle.Context(new MaterialId("r","a"),0,true,target,512,Vector2.one,Vector2.zero,materialState,true,AtlasTextureSemantic.BaseColor),contexts[1]}; Assert.That(AtlasMeshStructureOracle.TryValidateForAtlasAcceptance(source,output,invalidExcluded,layout,state,state,out var excluded),Is.False); Assert.That(excluded.domainCode,Is.EqualTo("AtlasMeshStructureTargetExclusionMismatch")); Object.DestroyImmediate(source);Object.DestroyImmediate(output);
  }
  [Test] public void TryValidate_RejectsTopologyAndMaterialStScopeChanges()
  {
   Mesh source=Mesh(); Mesh output=Object.Instantiate(source); var cell=new AtlasLayoutCell(new MaterialId("r","a"),0,0,0,256,256,0); output.uv=new[]{AtlasUvTransform.Apply(source.uv[0],Vector2.one,Vector2.zero,cell,512),AtlasUvTransform.Apply(source.uv[1],Vector2.one,Vector2.zero,cell,512),AtlasUvTransform.Apply(source.uv[2],Vector2.one,Vector2.zero,cell,512),source.uv[3],source.uv[4],source.uv[5]}; var unchanged=new AtlasMeshStructureOracle.MaterialState(new Vector4(2,1,.25f,0),new Vector4(2,1,.25f,0)); var contexts=new[]{new AtlasMeshStructureOracle.Context(new MaterialId("r","a"),0,true,cell,512,Vector2.one,Vector2.zero,new AtlasMeshStructureOracle.MaterialState(new Vector4(1,1,0,0),new Vector4(1,1,0,0)),false,AtlasTextureSemantic.BaseColor),new AtlasMeshStructureOracle.Context(new MaterialId("r","b"),1,false,null,0,Vector2.one,Vector2.zero,unchanged,false,AtlasTextureSemantic.Normal)};
   Assert.That(AtlasMeshStructureOracle.TryValidate(source,output,contexts,out var ok),Is.True,ok?.message); output.SetIndices(source.GetIndices(0),MeshTopology.Points,0); Assert.That(AtlasMeshStructureOracle.TryValidate(source,output,contexts,out var topology),Is.False); Assert.That(topology.domainCode,Is.EqualTo("AtlasMeshStructureTopologyChanged")); output.SetTriangles(source.GetIndices(0),0); var targetSt=new[]{new AtlasMeshStructureOracle.Context(new MaterialId("r","a"),0,true,cell,512,Vector2.one,Vector2.zero,new AtlasMeshStructureOracle.MaterialState(new Vector4(1,1,0,0),new Vector4(2,1,0,0)),false,AtlasTextureSemantic.BaseColor),contexts[1]}; Assert.That(AtlasMeshStructureOracle.TryValidate(source,output,targetSt,out var target),Is.False); Assert.That(target.domainCode,Is.EqualTo("AtlasMeshStructureMaterialStScope")); var untouchedSt=new[]{contexts[0],new AtlasMeshStructureOracle.Context(new MaterialId("r","b"),1,false,null,0,Vector2.one,Vector2.zero,new AtlasMeshStructureOracle.MaterialState(new Vector4(2,1,.25f,0),new Vector4(1,1,0,0)),false,AtlasTextureSemantic.Normal)}; Assert.That(AtlasMeshStructureOracle.TryValidate(source,output,untouchedSt,out var nonTarget),Is.False); Assert.That(nonTarget.domainCode,Is.EqualTo("AtlasMeshStructureMaterialStScope")); Object.DestroyImmediate(source);Object.DestroyImmediate(output);
  }
  [Test] public void TryValidate_RequiresExplicitMaterialStateSemanticAndFiniteUvset()
  {
   Mesh source=Mesh(); Mesh output=Object.Instantiate(source); var material=new AtlasMeshStructureOracle.MaterialState(new Vector4(1,1,0,0),new Vector4(1,1,0,0)); var missing=new[]{new AtlasMeshStructureOracle.Context(new MaterialId("r","a"),0,false,null,0,Vector2.one,Vector2.zero),new AtlasMeshStructureOracle.Context(new MaterialId("r","b"),1,false,null,0,Vector2.one,Vector2.zero,material,false,AtlasTextureSemantic.Normal)}; Assert.That(AtlasMeshStructureOracle.TryValidate(source,output,missing,out var required),Is.False); Assert.That(required.domainCode,Is.EqualTo("AtlasMeshStructureContextInvalid")); var nonFinite=new[]{new AtlasMeshStructureOracle.Context(new MaterialId("r","a"),0,false,null,0,new Vector2(float.NaN,1),Vector2.zero,material,false,AtlasTextureSemantic.BaseColor),missing[1]}; Assert.That(AtlasMeshStructureOracle.TryValidate(source,output,nonFinite,out var finite),Is.False); Assert.That(finite.domainCode,Is.EqualTo("AtlasMeshStructureContextInvalid")); Object.DestroyImmediate(source);Object.DestroyImmediate(output);
  }
  [Test] public void TryValidateForAtlasAcceptance_RequiresTargetExclusionPartitionAndAcceptsAllExcluded()
  {
   Mesh source=Mesh(); Mesh output=Object.Instantiate(source); var material=new AtlasMeshStructureOracle.MaterialState(new Vector4(2,1,.25f,0),new Vector4(2,1,.25f,0)); var contexts=new[]{new AtlasMeshStructureOracle.Context(new MaterialId("r","a"),0,false,null,0,Vector2.one,Vector2.zero,material,true,AtlasTextureSemantic.BaseColor),new AtlasMeshStructureOracle.Context(new MaterialId("r","b"),1,false,null,0,Vector2.one,Vector2.zero,material,true,AtlasTextureSemantic.Normal)}; var layout=new AtlasLayoutResult(512,new AtlasSemanticPage[0],new AtlasLayoutCell[0]); var state=new AtlasMeshStructureOracle.RendererState(new[]{new MaterialId("r","a"),new MaterialId("r","b")},"root","avatar"); Assert.That(AtlasMeshStructureOracle.TryValidateForAtlasAcceptance(source,output,contexts,layout,state,state,out var allExcluded),Is.True,allExcluded?.message); var mismatch=new[]{new AtlasMeshStructureOracle.Context(new MaterialId("r","a"),0,false,null,0,Vector2.one,Vector2.zero,material,false,AtlasTextureSemantic.BaseColor),contexts[1]}; Assert.That(AtlasMeshStructureOracle.TryValidateForAtlasAcceptance(source,output,mismatch,layout,state,state,out var diagnostic),Is.False); Assert.That(diagnostic.domainCode,Is.EqualTo("AtlasMeshStructureTargetExclusionMismatch")); Object.DestroyImmediate(source);Object.DestroyImmediate(output);
  }
  [Test] public void TryValidateForAtlasAcceptance_BindsTargetUvsetToOriginalMaterialSt()
  {
   Mesh source=Mesh(); Mesh output=Object.Instantiate(source); var cell=new AtlasLayoutCell(new MaterialId("r","a"),0,0,0,256,256,0); var originalSt=new Vector4(.5f,.5f,.25f,.25f); var targetMaterial=new AtlasMeshStructureOracle.MaterialState(originalSt,new Vector4(1,1,0,0)); output.uv=new[]{AtlasUvTransform.Apply(source.uv[0],new Vector2(originalSt.x,originalSt.y),new Vector2(originalSt.z,originalSt.w),cell,512),AtlasUvTransform.Apply(source.uv[1],new Vector2(originalSt.x,originalSt.y),new Vector2(originalSt.z,originalSt.w),cell,512),AtlasUvTransform.Apply(source.uv[2],new Vector2(originalSt.x,originalSt.y),new Vector2(originalSt.z,originalSt.w),cell,512),source.uv[3],source.uv[4],source.uv[5]}; var excludedMaterial=new AtlasMeshStructureOracle.MaterialState(new Vector4(2,1,0,0),new Vector4(2,1,0,0)); var contexts=new[]{new AtlasMeshStructureOracle.Context(new MaterialId("r","a"),0,true,cell,512,new Vector2(originalSt.x,originalSt.y),new Vector2(originalSt.z,originalSt.w),targetMaterial,false,AtlasTextureSemantic.BaseColor),new AtlasMeshStructureOracle.Context(new MaterialId("r","b"),1,false,null,0,Vector2.one,Vector2.zero,excludedMaterial,true,AtlasTextureSemantic.Normal)}; var layout=new AtlasLayoutResult(512,new[]{new AtlasSemanticPage(0,AtlasTextureSemantic.BaseColor,512),new AtlasSemanticPage(0,AtlasTextureSemantic.Normal,512)},new[]{cell}); var state=new AtlasMeshStructureOracle.RendererState(new[]{new MaterialId("r","a"),new MaterialId("r","b")},"root","avatar"); Assert.That(AtlasMeshStructureOracle.TryValidateForAtlasAcceptance(source,output,contexts,layout,state,state,out var ok),Is.True,ok?.message); var wrongScale=new[]{new AtlasMeshStructureOracle.Context(new MaterialId("r","a"),0,true,cell,512,Vector2.one,new Vector2(originalSt.z,originalSt.w),targetMaterial,false,AtlasTextureSemantic.BaseColor),contexts[1]}; Assert.That(AtlasMeshStructureOracle.TryValidateForAtlasAcceptance(source,output,wrongScale,layout,state,state,out var scale),Is.False); Assert.That(scale.domainCode,Is.EqualTo("AtlasMeshStructureUvsetMaterialStMismatch")); var wrongOffset=new[]{new AtlasMeshStructureOracle.Context(new MaterialId("r","a"),0,true,cell,512,new Vector2(originalSt.x,originalSt.y),Vector2.zero,targetMaterial,false,AtlasTextureSemantic.BaseColor),contexts[1]}; Assert.That(AtlasMeshStructureOracle.TryValidateForAtlasAcceptance(source,output,wrongOffset,layout,state,state,out var offset),Is.False); Assert.That(offset.domainCode,Is.EqualTo("AtlasMeshStructureUvsetMaterialStMismatch")); Object.DestroyImmediate(source);Object.DestroyImmediate(output);
  }
  [Test] public void TryValidateForAtlasAcceptance_RequiresBitExactMaterialSt()
  {
   Mesh source=Mesh(); Mesh output=Object.Instantiate(source); var cell=new AtlasLayoutCell(new MaterialId("r","a"),0,0,0,256,256,0); output.uv=new[]{AtlasUvTransform.Apply(source.uv[0],Vector2.one,Vector2.zero,cell,512),AtlasUvTransform.Apply(source.uv[1],Vector2.one,Vector2.zero,cell,512),AtlasUvTransform.Apply(source.uv[2],Vector2.one,Vector2.zero,cell,512),source.uv[3],source.uv[4],source.uv[5]}; var identity=new Vector4(1,1,0,0); var retained=new Vector4(2,1,.25f,0); var contexts=new[]{new AtlasMeshStructureOracle.Context(new MaterialId("r","a"),0,true,cell,512,Vector2.one,Vector2.zero,new AtlasMeshStructureOracle.MaterialState(identity,identity),false,AtlasTextureSemantic.BaseColor),new AtlasMeshStructureOracle.Context(new MaterialId("r","b"),1,false,null,0,Vector2.one,Vector2.zero,new AtlasMeshStructureOracle.MaterialState(retained,retained),true,AtlasTextureSemantic.Normal)}; var layout=new AtlasLayoutResult(512,new[]{new AtlasSemanticPage(0,AtlasTextureSemantic.BaseColor,512),new AtlasSemanticPage(0,AtlasTextureSemantic.Normal,512)},new[]{cell}); var state=new AtlasMeshStructureOracle.RendererState(new[]{new MaterialId("r","a"),new MaterialId("r","b")},"root","avatar"); Assert.That(AtlasMeshStructureOracle.TryValidateForAtlasAcceptance(source,output,contexts,layout,state,state,out var ok),Is.True,ok?.message); float oneBitFromOne=BitConverter.Int32BitsToSingle(BitConverter.SingleToInt32Bits(1f)+1); var targetChanged=new[]{new AtlasMeshStructureOracle.Context(new MaterialId("r","a"),0,true,cell,512,Vector2.one,Vector2.zero,new AtlasMeshStructureOracle.MaterialState(identity,new Vector4(oneBitFromOne,1,0,0)),false,AtlasTextureSemantic.BaseColor),contexts[1]}; Assert.That(AtlasMeshStructureOracle.TryValidateForAtlasAcceptance(source,output,targetChanged,layout,state,state,out var target),Is.False); Assert.That(target.domainCode,Is.EqualTo("AtlasMeshStructureMaterialStScope")); float oneBitFromRetained=BitConverter.Int32BitsToSingle(BitConverter.SingleToInt32Bits(retained.x)+1); var excludedChanged=new[]{contexts[0],new AtlasMeshStructureOracle.Context(new MaterialId("r","b"),1,false,null,0,Vector2.one,Vector2.zero,new AtlasMeshStructureOracle.MaterialState(retained,new Vector4(oneBitFromRetained,1,.25f,0)),true,AtlasTextureSemantic.Normal)}; Assert.That(AtlasMeshStructureOracle.TryValidateForAtlasAcceptance(source,output,excludedChanged,layout,state,state,out var excluded),Is.False); Assert.That(excluded.domainCode,Is.EqualTo("AtlasMeshStructureMaterialStScope")); Object.DestroyImmediate(source);Object.DestroyImmediate(output);
  }
  [Test] public void TryValidateForAtlasAcceptance_RejectsVertexAndTriangleIndexChanges()
  {
   Mesh source=Mesh(); var cell=new AtlasLayoutCell(new MaterialId("r","a"),0,0,0,256,256,0); var material=new AtlasMeshStructureOracle.MaterialState(new Vector4(1,1,0,0),new Vector4(1,1,0,0)); var contexts=new[]{new AtlasMeshStructureOracle.Context(new MaterialId("r","a"),0,true,cell,512,Vector2.one,Vector2.zero,material,false,AtlasTextureSemantic.BaseColor),new AtlasMeshStructureOracle.Context(new MaterialId("r","b"),1,false,null,0,Vector2.one,Vector2.zero,material,true,AtlasTextureSemantic.Normal)}; var layout=new AtlasLayoutResult(512,new[]{new AtlasSemanticPage(0,AtlasTextureSemantic.BaseColor,512),new AtlasSemanticPage(0,AtlasTextureSemantic.Normal,512)},new[]{cell}); var state=new AtlasMeshStructureOracle.RendererState(new[]{new MaterialId("r","a"),new MaterialId("r","b")},"root","avatar"); Mesh vertexChanged=Object.Instantiate(source); vertexChanged.vertices=new[]{Vector3.zero,Vector3.right,Vector3.up,new Vector3(2,0),new Vector3(3,0),new Vector3(2,1),new Vector3(4,1)}; Assert.That(AtlasMeshStructureOracle.TryValidateForAtlasAcceptance(source,vertexChanged,contexts,layout,state,state,out var vertex),Is.False); Assert.That(vertex.domainCode,Is.EqualTo("AtlasMeshStructureChanged")); Mesh indexChanged=Object.Instantiate(source); indexChanged.uv=new[]{AtlasUvTransform.Apply(source.uv[0],Vector2.one,Vector2.zero,cell,512),AtlasUvTransform.Apply(source.uv[1],Vector2.one,Vector2.zero,cell,512),AtlasUvTransform.Apply(source.uv[2],Vector2.one,Vector2.zero,cell,512),source.uv[3],source.uv[4],source.uv[5]}; indexChanged.SetTriangles(new[]{0,2,1},0); Assert.That(AtlasMeshStructureOracle.TryValidateForAtlasAcceptance(source,indexChanged,contexts,layout,state,state,out var triangle),Is.False); Assert.That(triangle.domainCode,Is.EqualTo("AtlasMeshStructureIndicesChanged")); Object.DestroyImmediate(source);Object.DestroyImmediate(vertexChanged);Object.DestroyImmediate(indexChanged);
  }
  [Test] public void TryValidateForAtlasAcceptance_RejectsSubmeshCountAndBlendShapeOrderChanges()
  {
   Mesh source=Mesh(); var zero=new Vector3[6]; source.AddBlendShapeFrame("a",100f,zero,zero,zero); source.AddBlendShapeFrame("b",100f,zero,zero,zero); var cell=new AtlasLayoutCell(new MaterialId("r","a"),0,0,0,256,256,0); var material=new AtlasMeshStructureOracle.MaterialState(new Vector4(1,1,0,0),new Vector4(1,1,0,0)); var contexts=new[]{new AtlasMeshStructureOracle.Context(new MaterialId("r","a"),0,true,cell,512,Vector2.one,Vector2.zero,material,false,AtlasTextureSemantic.BaseColor),new AtlasMeshStructureOracle.Context(new MaterialId("r","b"),1,false,null,0,Vector2.one,Vector2.zero,material,true,AtlasTextureSemantic.Normal)}; var layout=new AtlasLayoutResult(512,new[]{new AtlasSemanticPage(0,AtlasTextureSemantic.BaseColor,512),new AtlasSemanticPage(0,AtlasTextureSemantic.Normal,512)},new[]{cell}); var state=new AtlasMeshStructureOracle.RendererState(new[]{new MaterialId("r","a"),new MaterialId("r","b")},"root","avatar"); Mesh submeshChanged=Object.Instantiate(source); submeshChanged.subMeshCount=3; Assert.That(AtlasMeshStructureOracle.TryValidateForAtlasAcceptance(source,submeshChanged,contexts,layout,state,state,out var submesh),Is.False); Assert.That(submesh.domainCode,Is.EqualTo("AtlasMeshStructureChanged")); Mesh orderChanged=Object.Instantiate(source); orderChanged.ClearBlendShapes(); orderChanged.AddBlendShapeFrame("b",100f,zero,zero,zero); orderChanged.AddBlendShapeFrame("a",100f,zero,zero,zero); Assert.That(AtlasMeshStructureOracle.TryValidateForAtlasAcceptance(source,orderChanged,contexts,layout,state,state,out var order),Is.False); Assert.That(order.domainCode,Is.EqualTo("AtlasMeshStructureBlendShapeChanged")); Object.DestroyImmediate(source);Object.DestroyImmediate(submeshChanged);Object.DestroyImmediate(orderChanged);
  }
  static Mesh Mesh(){var m=new Mesh();m.vertices=new[]{Vector3.zero,Vector3.right,Vector3.up,new Vector3(2,0),new Vector3(3,0),new Vector3(2,1)};m.uv=new[]{Vector2.zero,Vector2.right,Vector2.up,Vector2.zero,Vector2.right,Vector2.up};m.subMeshCount=2;m.SetTriangles(new[]{0,1,2},0);m.SetTriangles(new[]{3,4,5},1);return m;}
 }
}
